import fs from 'node:fs';
import path from 'node:path';
import type { Configuration } from '../config/schema.js';
import {
  buildCodexHooksJson,
  mergeCodexHooksIntoFile,
  type CodexHooksBlock,
  type CodexHooksFile,
} from '../hooks/mapping.js';
import {
  agentsMdCustomAndDirectories,
  agentsMdPreamble,
} from './agents-md.js';
import { readManifest } from '../library/manifest.js';
import { collectRuleIds, collectSkillIds } from '../library/presets.js';
import { readRuleParts, readSkillContent } from '../library/load-assets.js';
import { isRootDirectoryKey, manifestIdToSafeFilename } from './shared.js';
import { customRuleToText, mergeInstructionBodies } from './merge-rules.js';

function ruleBodyToInstruction(metaDescription: string, body: string): string {
  return `## ${metaDescription}\n\n${body.trim()}`;
}

function readCodexHooksFile(p: string): CodexHooksFile | undefined {
  if (!fs.existsSync(p)) return undefined;
  try {
    const raw: unknown = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (
      typeof raw !== 'object' ||
      raw === null ||
      !('hooks' in raw) ||
      typeof (raw as { hooks: unknown }).hooks !== 'object' ||
      (raw as { hooks: unknown }).hooks === null
    ) {
      return undefined;
    }
    return {
      hooks: (raw as { hooks: CodexHooksBlock }).hooks,
    };
  } catch {
    return undefined;
  }
}

/**
 * OpenAI Codex: root (and nested) `AGENTS.md`, repo skills under `.agents/skills/`
 * (see https://developers.openai.com/codex/skills), and optional `.codex/hooks.json`
 * (see https://developers.openai.com/codex/hooks; enable with `codex_hooks` in config).
 */
export function generateCodex(
  cwd: string,
  config: Configuration,
  libraryRoot: string,
): void {
  const manifest = readManifest(libraryRoot);
  const ruleIds = collectRuleIds(manifest, config);
  const skillIds = collectSkillIds(manifest, config);

  const sections: string[] = [
    ...agentsMdPreamble(config),
    '\n## Bundled library rules (dossier)\n',
    'The following sections are generated from the dossier library for this repo’s languages and frameworks.\n',
  ];

  for (const id of ruleIds) {
    const { meta, body } = readRuleParts(libraryRoot, id);
    sections.push(ruleBodyToInstruction(meta.description, body));
  }

  sections.push(...agentsMdCustomAndDirectories(config));

  fs.writeFileSync(
    path.join(cwd, 'AGENTS.md'),
    `${sections.map((p) => p.trimEnd()).join('\n\n')}\n`,
    'utf8',
  );

  const skillsRoot = path.join(cwd, '.agents', 'skills');

  for (const id of skillIds) {
    const content = readSkillContent(libraryRoot, id);
    const dirName = manifestIdToSafeFilename(id);
    const skillDir = path.join(skillsRoot, dirName);
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), content, 'utf8');
  }

  const customGlobal = config.customRules.map(customRuleToText);
  if (customGlobal.length > 0) {
    const skillDir = path.join(skillsRoot, 'dossier-custom-global');
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      `---\nname: dossier-custom-global\ndescription: Repository-wide custom rules from dossier config\n---\n\n${mergeInstructionBodies(customGlobal)}\n`,
      'utf8',
    );
  }

  let d = 0;
  for (const [dirPath, dirConfig] of Object.entries(config.directories)) {
    const scoped = dirConfig.customRules.map(customRuleToText);
    if (scoped.length === 0) continue;
    if (isRootDirectoryKey(dirPath)) continue;
    const name = `dossier-custom-dir-${d++}`;
    const skillDir = path.join(skillsRoot, name);
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      `---\nname: ${name}\ndescription: Custom rules for ${dirPath.replace(/\/$/, '')}\n---\n\n${mergeInstructionBodies(scoped)}\n`,
      'utf8',
    );
  }

  if (config.hooks.length > 0) {
    const hooksPath = path.join(cwd, '.codex', 'hooks.json');
    fs.mkdirSync(path.dirname(hooksPath), { recursive: true });
    const existing = readCodexHooksFile(hooksPath);
    const generated = buildCodexHooksJson(config.hooks);
    const merged = mergeCodexHooksIntoFile(existing, generated);
    fs.writeFileSync(
      hooksPath,
      `${JSON.stringify(merged, null, 2)}\n`,
      'utf8',
    );
  }

  for (const [dirPath, dirConfig] of Object.entries(config.directories)) {
    if (isRootDirectoryKey(dirPath)) continue;
    const scoped = dirConfig.customRules.map(customRuleToText);
    if (scoped.length === 0) continue;
    const dirAbs = path.join(cwd, dirPath.replace(/\/$/, ''));
    fs.mkdirSync(dirAbs, { recursive: true });
    const label = dirPath.replace(/\/$/, '');
    const content = `# Directory instructions (${label})

Generated by [dossier](https://www.npmjs.com/package/@clew-ai/dossier) for OpenAI Codex. Regenerate with \`dossier generate codex\`.

${mergeInstructionBodies(scoped)}
`;
    fs.writeFileSync(path.join(dirAbs, 'AGENTS.md'), content, 'utf8');
  }
}
