import fs from 'node:fs';
import path from 'node:path';
import type { Configuration } from '../config/schema.js';
import { readManifest } from '../library/manifest.js';
import { collectRuleIds } from '../library/presets.js';
import { readRuleParts } from '../library/load-assets.js';
import { copilotApplyToGlob, isRootDirectoryKey } from './shared.js';
import { customRuleToText, mergeInstructionBodies } from './merge-rules.js';

function ruleBodyToInstruction(metaDescription: string, body: string): string {
  return `## ${metaDescription}\n\n${body.trim()}`;
}

export function generateCopilot(
  cwd: string,
  config: Configuration,
  libraryRoot: string,
): void {
  const manifest = readManifest(libraryRoot);
  const ruleIds = collectRuleIds(manifest, config);

  const globalParts: string[] = [
    '# Copilot instructions (generated by dossier)\n',
    'Regenerate with `dossier generate copilot`. Config: `.dossier/config.json`.\n',
  ];

  for (const id of ruleIds) {
    const { meta, body } = readRuleParts(libraryRoot, id);
    globalParts.push(ruleBodyToInstruction(meta.description, body));
  }

  const customGlobal = config.customRules.map(customRuleToText);
  if (customGlobal.length > 0) {
    globalParts.push('## Custom (repository-wide)\n');
    globalParts.push(mergeInstructionBodies(customGlobal));
  }

  const githubDir = path.join(cwd, '.github');
  fs.mkdirSync(githubDir, { recursive: true });
  fs.writeFileSync(
    path.join(githubDir, 'copilot-instructions.md'),
    `${globalParts.map((p) => p.trim()).join('\n\n')}\n`,
    'utf8',
  );

  const instructionsDir = path.join(githubDir, 'instructions');
  let idx = 0;
  for (const [dirPath, dirConfig] of Object.entries(config.directories)) {
    const scoped = dirConfig.customRules.map(customRuleToText);
    if (scoped.length === 0) continue;
    fs.mkdirSync(instructionsDir, { recursive: true });
    const applyGlob = copilotApplyToGlob(dirPath);
    const label = isRootDirectoryKey(dirPath) ? 'root' : dirPath;
    const content = `---
applyTo: "${applyGlob}"
---
# Directory-specific instructions (${label})

${mergeInstructionBodies(scoped)}
`;
    fs.writeFileSync(
      path.join(instructionsDir, `dossier-dir-${idx++}.md`),
      content,
      'utf8',
    );
  }
}
